import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
}

/** Version shown in the app (Android also sets it in app/build.gradle.kts; iOS reads its Info.plist). */
val appVersionName = providers.gradleProperty("riderange.versionName").get()

kotlin {
    androidLibrary {
        namespace = "com.elect.riderange.shared"
        compileSdk = 37
        minSdk = 26
        withHostTestBuilder {}.configure {}
    }

    listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
        optIn.add("kotlin.uuid.ExperimentalUuidApi")
        optIn.add("kotlin.time.ExperimentalTime")
        optIn.add("kotlin.io.encoding.ExperimentalEncodingApi")
        optIn.add("kotlinx.cinterop.ExperimentalForeignApi")
        optIn.add("kotlinx.cinterop.BetaInteropApi")
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/appinfo"))
            dependencies {
                implementation(libs.cmp.runtime)
                implementation(libs.cmp.foundation)
                implementation(libs.cmp.ui)
                implementation(libs.cmp.material3)
                implementation(libs.cmp.icons.extended)
                implementation(libs.jb.lifecycle.viewmodel.compose)
                implementation(libs.jb.lifecycle.runtime.compose)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.datetime)
                implementation(libs.androidx.room.runtime)
                api(libs.androidx.datastore.preferences.core)
            }
        }
        commonTest {
            kotlin.srcDir(layout.buildDirectory.dir("generated/testpaths"))
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }
        androidMain.dependencies {
            implementation(libs.androidx.core.ktx)
            implementation(libs.androidx.datastore.preferences)
            implementation(libs.maplibre.android)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.androidx.lifecycle.runtime.ktx)
        }
        iosMain.dependencies {
            implementation(libs.androidx.sqlite.bundled)
        }
    }
}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
}

room {
    schemaDirectory("$projectDir/schemas")
}

// Build-time constants for common code (no BuildConfig in Kotlin Multiplatform).
val genAppInfo by tasks.registering {
    val out = layout.buildDirectory.dir("generated/appinfo")
    val version = appVersionName
    inputs.property("version", version)
    outputs.dir(out)
    doLast {
        val f = out.get().file("com/elect/riderange/core/AppVersion.kt").asFile
        f.parentFile.mkdirs()
        f.writeText("package com.elect.riderange.core\n\n/** Generated by shared/build.gradle.kts. */\nconst val APP_VERSION_NAME = \"$version\"\n")
    }
}

// Test fixtures live on disk: the JVM and the iOS simulator can both read the checkout directly.
val genTestPaths by tasks.registering {
    val out = layout.buildDirectory.dir("generated/testpaths")
    val res = file("src/commonTest/resources").absolutePath.replace('\\', '/')
    val assets = rootProject.file("app/src/main/assets").absolutePath.replace('\\', '/')
    val sources = file("src/commonMain/kotlin").absolutePath.replace('\\', '/')
    inputs.property("res", res)
    inputs.property("assets", assets)
    inputs.property("sources", sources)
    outputs.dir(out)
    doLast {
        val f = out.get().file("com/elect/riderange/TestPaths.kt").asFile
        f.parentFile.mkdirs()
        f.writeText("package com.elect.riderange\n\ninternal object TestPaths {\n    const val RESOURCES = \"$res\"\n" +
            "    const val ASSETS = \"$assets\"\n    const val SOURCES = \"$sources\"\n}\n")
    }
}

tasks.matching { it.name.startsWith("compile") || it.name.startsWith("ksp") }.configureEach {
    dependsOn(genAppInfo, genTestPaths)
}

// CI picks a simulator that exists on the runner's Xcode (IOS_SIM_DEVICE, e.g. "iPhone 17").
tasks.withType<org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest>().configureEach {
    providers.environmentVariable("IOS_SIM_DEVICE").orNull?.let { device.set(it) }
}
